// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMz78e_RJDbdZCxYdLkhQ9DCFlkGpfCVo',
    appId: '1:421853839980:web:a01b88f24b31ed50624e49',
    messagingSenderId: '421853839980',
    projectId: 'crypto-list-app-ea736',
    authDomain: 'crypto-list-app-ea736.firebaseapp.com',
    storageBucket: 'crypto-list-app-ea736.appspot.com',
    measurementId: 'G-RTESM3897J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHImf6_RwBneATgi3KBThrQl3rNOIen5c',
    appId: '1:421853839980:android:b77adabdf25e0b3d624e49',
    messagingSenderId: '421853839980',
    projectId: 'crypto-list-app-ea736',
    storageBucket: 'crypto-list-app-ea736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0QFASi859onWO_KxmTG7fdKqOkXXRtd4',
    appId: '1:421853839980:ios:1cae3947b192c1c1624e49',
    messagingSenderId: '421853839980',
    projectId: 'crypto-list-app-ea736',
    storageBucket: 'crypto-list-app-ea736.appspot.com',
    iosBundleId: 'com.cryptoguys.criptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0QFASi859onWO_KxmTG7fdKqOkXXRtd4',
    appId: '1:421853839980:ios:1cae3947b192c1c1624e49',
    messagingSenderId: '421853839980',
    projectId: 'crypto-list-app-ea736',
    storageBucket: 'crypto-list-app-ea736.appspot.com',
    iosBundleId: 'com.cryptoguys.criptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMz78e_RJDbdZCxYdLkhQ9DCFlkGpfCVo',
    appId: '1:421853839980:web:9235edc562dc338d624e49',
    messagingSenderId: '421853839980',
    projectId: 'crypto-list-app-ea736',
    authDomain: 'crypto-list-app-ea736.firebaseapp.com',
    storageBucket: 'crypto-list-app-ea736.appspot.com',
    measurementId: 'G-8KJTMVDYR2',
  );
}
